name: Build FreshX API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - run: dotnet restore
      - run: dotnet build

      # - name: Create SSH key
      #   run: |
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
      #     chmod 600 private_key.pem

      # - name: Clean deploy folder
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i private_key.pem user@100.95.37.29 'rm -rf /path/to/deploy/*'

      # - name: Copy files
      #   run: |
      #     scp -o StrictHostKeyChecking=no -i private_key.pem -r ./publish/* user@100.95.37.29:/path/to/deploy/

      # - name: Restart app
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i private_key.pem user@100.95.37.29 '
      #       pkill -f freshx_api.dll || true
      #       nohup dotnet /path/to/deploy/freshx_api.dll > app.log 2>&1 &
      #     '
